/**
 * Virtual module generated by the `svelteFluentUI` Vite plugin.
 *
 * Maps `"<name>_<size>_<variant>"` (e.g. `"subtract_16_regular"`) to either the
 * icon's raw SVG markup (`inline` mode) or its emitted asset URL (`asset` mode).
 * The `Icon` component distinguishes the two by whether the value starts with `<`.
 */
declare module 'virtual:fluentui-icons' {
	const icons: Record<string, string>;
	export default icons;
}
