import {readFileSync, writeFileSync} from "fs"
import path from "path"
import {fileURLToPath} from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const rootDir = path.resolve(__dirname, "..")

const pkgPath = path.join(rootDir, "package.json")
const versionFile = path.join(rootDir, "src", "lib", "version.ts")

const pkg = JSON.parse(readFileSync(pkgPath, "utf8"))
const contents = `// Auto-generated by scripts/pre-package.js — do NOT edit by hand.
// In dev this file holds whatever value was committed last; on each \`npm run package\`
// the pre-package script overwrites it with the current package.json version.
export const VERSION = "${pkg.version}"
`

writeFileSync(versionFile, contents)
console.log(`✓ src/lib/version.ts → VERSION = "${pkg.version}"`)
