// Auto-generated by scripts/pre-package.js — do NOT edit by hand.
// In dev this file holds whatever value was committed last; on each `npm run package`
// the pre-package script overwrites it with the current package.json version.
export const VERSION = "1.0.0-rc12"
